### ISSUE TITLE
Feature Request - Add polling interval in options flow

### ISSUE THREAD

**Issue by djtimca** [djtimca/HASpaceX#10]
Add the ability to set a custom polling interval in the configuration options flow.

**Comment by djtimca** [comment]
It doesn't appear at this time that an Options Flow is possible on an integration which uses the discovery method. Because there is no authentication needed to pull the SpaceX data there is no reason to use a full config flow and therefore no way to add the options flow. If this changes in the future I will address this.

**Comment by meichthys** [comment]
Not a huge issue obviously, but for reference, my AdguardHome is showing this integration as my top DNS query. (I've only been running AdguardHome for a single day, so even though it says 30 days, it is only showing 1 day of queries:
<img width="571" alt="Screen Shot 2021-05-22 at 8 53 34 PM" src="https://user-images.githubusercontent.com/10717998/119244540-cd803f80-bb3f-11eb-8ffa-a52e5a90b0e6.png">
