### ISSUE TITLE
HA 117 - unable to add integration, not visible in HA

### ISSUE THREAD

**Issue by p1ranha** [djtimca/HASpaceX#11]
Trying to add the integration, and after installation from HACS, restarting HA it's not visible in Configuration -> Integrations -> +

**Comment by DarKOrange75** [comment]
Same issue here, installed from HACS and not present in the integration list

**Comment by djtimca** [comment]
Is there anything in your logs after restarting Home Assistant?

**Comment by DarKOrange75** [comment]
This was fixed after updating HA to latest core and supervisor versions. Sorry to bother you and thank you for your fast answer.
