### ISSUE TITLE
next launch date showing a past date

### ISSUE THREAD

**Issue by pinkywafer** [djtimca/HASpaceX#15]
not sure if this is related to #6
<img src="https://user-images.githubusercontent.com/8636233/99835318-5a7c1900-2b5c-11eb-8aa6-01bc8919f008.gif" width="400" >

For reference, today  is Friday 20 November, and the crew-1 mission launched on 16 November

**Comment by djtimca** [comment]
In this case SpaceX has not updated their data in the API (you can view it raw at: https://api.spacexdata.com/v3/launches/next).

I'm not sure I want to do a lot of pre-processing to manage logic if they don't update their data as it could potentially cause issues with time-zone differences etc.

Usually they are better about getting things updated sooner, but when they don't it will report funny looking info like this.

Interestingly the data from RocketLaunch.Live (my integration is at https://github.com/djtimca/harocketlaunchlive) does have the Michael Freilich launch from Vandenberg showing for tomorrow at 12:17 and Starlink-16 from Florida tomorrow at 10:17pm so not sure where they are pulling their info from.
