### ISSUE TITLE
Starman not updating?

### ISSUE THREAD

**Issue by mhertel** [djtimca/HASpaceX#22]
I have this installed into HA and the SpaceX data is coming in fine.
But I noticed the Starman data has been the same since I installed it..

![starman2](https://user-images.githubusercontent.com/4166847/102512673-24d52d80-403f-11eb-85d7-4e9fd45a4a7d.png)
![starman1](https://user-images.githubusercontent.com/4166847/102512676-256dc400-403f-11eb-9af8-0ecf2e3e2506.png)

I'm sure this should have changed in a week..

**Comment by djtimca** [comment]
The data in the API V4 doesn't seem to be updating from the source. I've opened an issue with them https://github.com/r-spacex/SpaceX-API/issues/605

The data you are seeing in the integration is correct to what is being fed from the API.

**Comment by mhertel** [comment]
Thanks for the quick response!

**Comment by djtimca** [comment]
Update has been made to source API so we should see improvements in this soon.
