### ISSUE TITLE
Mission Details cut off mid word....

### ISSUE THREAD

**Issue by 4meuwil** [djtimca/HASpaceX#23]
Any way to get the complete mission details or at least have it not cut off in the middle of a word in a sentence fragment?

Keep up the good work!

**Comment by djtimca** [comment]
Unfortunately Home Assistant has a 255 character limit. Prefer to include as much text as we can within that so it will just cut off at that limit.

**Comment by 4meuwil** [comment]
What about a details 1 and details 2? 🤷🏻‍♂️

**Comment by djtimca** [comment]
Possible - will look at it.

**Comment by 4meuwil** [comment]
Thank You!
