### ISSUE TITLE
Starman speed correct?

### ISSUE THREAD

**Issue by asemev** [djtimca/HASpaceX#26]
HI djtimca,

First of all, BIG thank you for this! Its so awesome :) I installed and configured it. Thank you!

I was just wondering. The starman speed shows 4094 km/h. Have i done something wrong?

Thanks.
-asemev

**Comment by djtimca** [comment]
That's the same value I have so I'm not sure.

**Comment by asemev** [comment]
ok thanks. Which API are the data coming from?

**Comment by asemev** [comment]
looking at this API, the speed is over 109,278 kmh...

https://api.spacexdata.com/v2/info/roadster

**Comment by asemev** [comment]
This also:  https://api.spacexdata.com/v3/roadster

**Comment by wdiz25** [comment]
@asemev This uses the version 4 API: https://api.spacexdata.com/v4/roadster. The data from version 3 [hasn't been updated since November 2020](https://docs.spacexdata.com). What is shown in Home Assistant matches the v4 data.
