### ISSUE TITLE
Feature Suggestion - SpaceX Updates

### ISSUE THREAD

**Issue by julianrinaldi** [djtimca/HASpaceX#31]
There is a guy on Twitter named [Brendan Lewis](https://twitter.com/_brendan_lewis/status/1422374894432522241) who makes great diagrams of current progress on Starship/Super Heavy/Starbase. I have set up a camera in my Home Assistant dashboard that uses these diagrams to put on my dashboard using a domain I bought and a static URL at http://spacexupdate.com/update.jpg which I update as new diagrams come out. Any interest in including a camera entity with your integration that points to this?

![CleanShot 2021-08-03 at 15 13 13](https://user-images.githubusercontent.com/492435/128072956-fb378de2-6d1e-40de-ad8f-e1ef8a180cc5.png)

**Comment by djtimca** [comment]
Interesting concept - will take a look

**Comment by djtimca** [comment]
Doesn't look like this image has been updated since August. I'd prefer not to add something that relies on a manual update to the integration. Thanks!
