### ISSUE TITLE
Integration Broken

### ISSUE THREAD

**Issue by tango2590** [djtimca/HASpaceX#37]
This integration doesn't seem to provide the expected sensors in HA. They just don't exist. Not sure if I'm doing something wrong or if it's broken
<img width="535" alt="Screen Shot 2021-12-25 at 18 17 12" src="https://user-images.githubusercontent.com/78666662/147395941-1392766c-04df-4696-a76c-032e0054ee41.png">
.

**Comment by djtimca** [comment]
Double check to see if there are other sensor with slightly different names. You may need to tweak the names for your install.

**Comment by tango2590** [comment]
It was me. I'm just an idiot. Helps when I actually integrate them into HA. xD

Thanks for your hard work on this integration!
