### ISSUE TITLE
Issues with 2022.5.x

### ISSUE THREAD

**Issue by SupremeSports** [djtimca/HASpaceX#39]
Just installed 2022.5 version of HA and it seems like it's missing the requirements "spacexpypi==0.0.12". How can I get it installed on HAOS virtual machine? Tried "pip install spacexpypi==0.0.12" and it fails to install

**Comment by djtimca** [comment]
Try a reboot of HA? I am running that version and no issues.

**Comment by SupremeSports** [comment]
> Try a reboot of HA? I am running that version and no issues.

Yeah, rebooted HA didn't work, had tried it few times. What did the trick was to reboot the host machine completely, not only the VM, but the whole computer. Thank you
