### ISSUE TITLE
Timezone of sensor.spacex_next_launch_time

### ISSUE THREAD

**Issue by Fakre** [djtimca/HASpaceX#4]
Hi, I just discovered your great Plugin for Home Assistant. Thank you for your excellent work!!

I have one little Problem that for me, it's not clear which time zone the sensor.spacex_next_launch_time displays. 
It would be great if you can add this.

Thank you!

**Comment by djtimca** [comment]
Thanks - it is pulling the local time for the launch which I believe SpaceX publishes as EST. I have also included the UTC time as an attribute so you  pull use that as well. Thanks!
