### ISSUE TITLE
Error fetching SpaceX data

### ISSUE THREAD

**Issue by XalaTheShepard** [djtimca/HASpaceX#46]
Log: 

Logger: custom_components.spacex
Source: helpers/update_coordinator.py:151
Integration: SpaceX Launches and Starman ([documentation](https://github.com/djtimca/haspacex), [issues](https://github.com/djtimca/HASpaceX/issues))
First occurred: September 5, 2022 at 9:20:31 PM (345 occurrences)
Last logged: 1:30:43 PM

Error fetching SpaceX data:

Since 5 September the SpaceX and Starman integration fails to fetch the data. 
After a reload, the information is available for maximum 1 minute and afterwards goes unavailable again. 
Might be a rate limit on the API.

**Comment by vincep5** [comment]
same with mine lately

**Comment by rpitera** [comment]
Ah, so it's not just me then.  : )

**Comment by LucaTino** [comment]
any news?

**Comment by djtimca** [comment]
Nope - thinking the API may be done. 

I've switched to relying on my Rocket Launch Live integration which has been much more reliable. 

I may mark this one as out of date.

**Comment by adam-olson** [comment]
Looks like the maintainer posted in their git hub back in October that winding down the project, see [https://github.com/r-spacex/SpaceX-API/issues/1243#issue-1402110647](https://github.com/r-spacex/SpaceX-API/issues/1243#issue-1402110647)

**Comment by djtimca** [comment]
Looks like that's it then for this integration... recommend you try the RocketLaunchLive integration instead.
