### ISSUE TITLE
SpaceX Integration not updated

### ISSUE THREAD

**Issue by robi59italy** [djtimca/HASpaceX#47]
Using last version 
Polling enable

it's not updated. Now it's showing a launch of 1st of november for "next launch"

<img width="241" alt="image" src="https://user-images.githubusercontent.com/63563817/201625699-68211036-3f87-4319-9436-dbc10b131fb8.png">

**Comment by deepcoder** [comment]
I am also seeing this on HA 2022.9.7 as well.

**Comment by djtimca** [comment]
Unfortunately the API driving the underlying data doesn't seem to be updating regularly. Recommend you also look at the other Rocket Launch integration I have at https://github.com/djtimca/harocketlaunchlive
