### ISSUE TITLE
Keeps popping up on hacs as new integration 

### ISSUE THREAD

**Issue by tbrasser** [djtimca/HASpaceX#49]
See title, not sure why it happens. But thought I'd let you know.

**Comment by Jurgenn22** [comment]
@djtimca,

Also with every restart off Home Assistant, i get this info line in my logs. I have not installed this integration in my Home Assistant setup, which makes it completely strange. It would be nice if you took a look at this. Would like to know what it is, if you know.
Thank you in advance.

INFO (MainThread) [custom_components.hacs] <Integration djtimca/HASpaceX> Starting removal

**Comment by johntdyer** [comment]
Yea, this is kinda driving me nuts :)

**Comment by djtimca** [comment]
Not sure what to suggest folks - HACS removed the integration as requested there. I've uninstalled from my instance and no issue. 

This integration is dead - make sure you remove it in your own instance.
