### ISSUE TITLE
next launch date showing a past date

### ISSUE THREAD

**Issue by IanAdd** [djtimca/HASpaceX#6]
Due the delaying of the Launch intended to be on Friday, the sensor is now showing me September 1 2020 10:00am. (AEST)
If the api returns a date in the past shouldn't you report N/A or similar ?

**Comment by mendhak** [comment]
For reference, I see the SpaceX API  https://api.spacexdata.com/v3/launches/next  is showing Sep 1 as the next launch date and today is Sep 19.  

`launch_date_utc: "2020-09-01T00:00:00.000Z"`

It does make sense to do a check on the value being sent back, maybe return some null value.  I don't know if @djtimca may prefer to do this check in here or their [Python library](https://github.com/djtimca/spacex-api/blob/master/spacexpypi/__init__.py).

**Comment by djtimca** [comment]
I could add an additional sensor for confirmed launch day for backwards compatibility and return unavailable when confirmed flag is false. That my be the cleanest solution. Will add this in the next release.

**Comment by 3ative** [comment]
@djtimca Sounds like the best way 👌
Great job on the integration BTW. Many Thanks. 👍

**Comment by djtimca** [comment]
Fixed in version 011 release. Also added device information and rewrote updates to better leverage the data coordinator from HA. Note will require version .115 now.
