### ISSUE TITLE
Data unavailable since installing 115.x

### ISSUE THREAD

**Issue by quiggles** [djtimca/HASpaceX#7]
Data unavailable since installing 115.x, tried reinstall but still not working.

**Comment by djtimca** [comment]
@quiggles do you have any errors in your logs? I have had no problems with data on 115 and still working correctly on 116b0.

Have you completely uninstalled the integration through HACS, rebooted, then reinstalled the integration and set it up again through Integrations?

**Comment by mattgahs** [comment]
I am having the same issue. It looks like the entities changed and the "spacex" string from the entities has been removed, so "sensor.spacex_latest_launch_time" is now "sensor.latest_launch_time". 

May need to update your Lovelace dashboards.

**Comment by djtimca** [comment]
Yes that is correct. That was listed as a breaking change. Entity ids changed as part of a previous update.
