### ISSUE TITLE
Feature Request: T-Countdown Timer

### ISSUE THREAD

**Issue by julianrinaldi** [djtimca/HASpaceX#8]
It would be amazing if this also had an entity for how long until the next launch, not just the time of the next launch. I'd love to be able to press a button on my dashboard and have one of my media players say "Next SpaceX launch in T-1 day, 2 hours, 3 minutes and 34 seconds" and so on. I've been meaning to figure this out on my own but dealing with dates in HA has been a bit confusing.

Thanks for the great integration!

**Comment by djtimca** [comment]
Released in version 019 which should now be available through HACS.

**Comment by djtimca** [comment]
@julianrinaldi FYI this adds next_launch_countdown which will be in DD:HH:MM:SS format but also has an attribute called t0_countdown which provides an english version of that X days, X hours, X minutes, X seconds until the launch of [mission_name] if you want to use that for Google Broadcast / TTS.

**Comment by julianrinaldi** [comment]
Wow, that's amazing. Thanks!
